# explicitly set the version of python and requirements
version: 2

build:
  os: "ubuntu-20.04"
  tools:
    python: "3.8"

python:
  install:
    - requirements: requirements.txt

mkdocs:
  configuration: mkdocs.yml
  