name: Build

on: [ push ]

concurrency:
  group: build
  cancel-in-progress: true


jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]
        python-version: [ '3.10', '3.11' ]
    steps:
      - name: Cleanup more disk space
        run: |
          sudo rm -rf /usr/share/dotnet || true
          sudo rm -rf /opt/ghc || true
          sudo rm -rf "/usr/local/share/boost" || true
          sudo rm -rf "$AGENT_TOOLSDIRECTORY" || true
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      - name: Install dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          python -m pip install --upgrade pip
          pip install ruff
          pip install -e ".[dev,gpu]" --extra-index-url https://download.pytorch.org/whl/cu121
      - name: Install dependencies (macOS)
        if: runner.os == 'macOS'
        run: |
          python -m pip install --upgrade pip
          pip install ruff
          pip install -e ".[dev]"
      - name: Lint with ruff
        run: |
          ruff check .
          ruff format --check .
      - name: Test with pytest
        run: |
          pytest
